### PR TITLE
Fix failing tests

### PR DESCRIPTION
**Pull request by haribhandari07**
## Questionnaire

- Where did you find the job? -> LinkedIn 
- Have you applied on the site above? -> No

## Agreement

- [x] I did not ask anyone for help to solve the problem.
- [x] I did not refer any other forks or pull requests of this repository.
- [x] I would make my fork private if requested after screening.

### CODE REVIEW

**Comment by hasundue** [comment]
Thank you for submission!

Almost perfect 😄 
But you still have to pass the CI on GitHub Actions.

**Comment by hasundue** [comment]
Thank you!
Can you request me a review?

**Comment by haribhandari07** [comment]
> Thank you! Can you request me a review?

Hi @hasundue, it seems like I don't have permission to make a review request.
Screenshot from 2022-09-22 14-55-35

**Comment by hasundue** [comment]
Oh I see, my bad.

**Review by hasundue — APPROVED** [review]
LGTM!

**Comment by haribhandari07** [comment]
@hasundue  should I make this private now?

**Comment by hasundue** [comment]
@HariBhandari07 No, you don't have to for now!
Sorry for my late reply 🙇‍♂️ 

Unfortunately, we are almost closing the position for this batch of hiring.
But we could still have a casual meeting or something if you'd like to.

**Comment by haribhandari07** [comment]
> most closing the position for this batch of hiring.
> But we could still have a casual meeting or something if you'd like to.

Sure, we can have a casual meeting.

**Comment by hasundue** [comment]
Roger. Let me consult with our HR team.

**Pull request closed without merging**
